### ISSUE TITLE
Python "make" on Mac

### ISSUE THREAD

**Issue by Sodaaaa** [smiths/swhs#22]
This is not exactly an issue, but when I first tried "make" (in Python) on my computer, it gave the following output:
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import event
  File "/Users/huangkeyu/swhs/Program/Python/event.py", line 1, in <module>
    import PyDSTool
  File "/Users/huangkeyu/Desktop/anaconda/lib/python3.5/site-packages/PyDSTool-0.90.2-py3.5.egg/PyDSTool/__init__.py", line 109, in <module>
    from .PyCont import *
  File "/Users/huangkeyu/Desktop/anaconda/lib/python3.5/site-packages/PyDSTool-0.90.2-py3.5.egg/PyDSTool/PyCont/__init__.py", line 3, in <module>
    from .ContClass import ContClass
  File "/Users/huangkeyu/Desktop/anaconda/lib/python3.5/site-packages/PyDSTool-0.90.2-py3.5.egg/PyDSTool/PyCont/ContClass.py", line 8, in <module>
    from .Continuation import (
  File "/Users/huangkeyu/Desktop/anaconda/lib/python3.5/site-packages/PyDSTool-0.90.2-py3.5.egg/PyDSTool/PyCont/Continuation.py", line 40, in <module>
    from .misc import *
  File "/Users/huangkeyu/Desktop/anaconda/lib/python3.5/site-packages/PyDSTool-0.90.2-py3.5.egg/PyDSTool/PyCont/misc.py", line 27, in <module>
    from PyDSTool.matplotlib_import import *
  File "/Users/huangkeyu/Desktop/anaconda/lib/python3.5/site-packages/PyDSTool-0.90.2-py3.5.egg/PyDSTool/matplotlib_import.py", line 11, in <module>
    import matplotlib
  File "/Users/huangkeyu/Desktop/anaconda/lib/python3.5/site-packages/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/Users/huangkeyu/Desktop/anaconda/lib/python3.5/site-packages/matplotlib/__init__.py", line 975, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/Users/huangkeyu/Desktop/anaconda/lib/python3.5/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/Users/huangkeyu/Desktop/anaconda/lib/python3.5/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/Users/huangkeyu/Desktop/anaconda/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Users/huangkeyu/Desktop/anaconda/lib/python3.5/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "/Users/huangkeyu/Desktop/anaconda/lib/python3.5/locale.py", line 559, in getdefaultlocale
    return _parse_localename(localename)
  File "/Users/huangkeyu/Desktop/anaconda/lib/python3.5/locale.py", line 487, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
make: *** [test.out] Error 1

However, I found online that this could be solved by adding two lines "export LC_ALL=en_US.UTF-8 \n export LANG=en_US.UTF-8" to "~/.bash_profile" and then typing "make" in a new shell window. (It works on my computer.)

I 'm currently not sure about the exact reason but this is something to do with the Mac OS X system.

**Comment by bmaclach** [comment]
I did some research on this error and it just seems to be a bug with Python on Mac OS X. I added a note to the Readme about it, including the solution you found.
